### ISSUE TITLE
App installs as 1.8.2 and cannot be updated

### ISSUE THREAD

**Issue by GameDevRogie** [fsvreddit/hive-protect#54]
When app is installed on a subreddit it installs as version 1.8.2 and clicking the update button to update to 1.9.0 gives an error and does not update.

**Comment by fsvreddit** [comment]
This is an issue at Reddit's end. 1.9.0 isn't yet publicly available (it's not been reviewed yet), yet Reddit is showing it as available for install/upgrade.

Generally speaking, if you see the "Unlisted" badge on an app's page, you can expect this to happen on a given app.

![image](https://github.com/user-attachments/assets/292a7aaf-1b56-4690-8f57-0db8ee1c8c07)

I have reported it to Reddit, hopefully they will fix it soon. Meanwhile, 1.9.0 has been submitted for review and should hopefully be able to be installed in 2-3 days.
